import { cacheGet, cacheSet } from '@/lib/cache'
import type { BairroCrimeData } from '@/lib/types'

const CACHE_KEY = 'crimeData'

export async function fetchCrimeData(): Promise<BairroCrimeData[]> {
  const cached = cacheGet<BairroCrimeData[]>(CACHE_KEY)
  if (cached && cached.length > 0) return cached

  // Try API route first (fetches real data from open data portal)
  try {
    const res = await fetch('/api/crime-data')
    if (res.ok) {
      const data: BairroCrimeData[] = await res.json()
      if (data.length > 0) {
        cacheSet(CACHE_KEY, data)
        return data
      }
    }
  } catch {
    // API route failed, try static fallback
  }

  // Fallback: try pre-processed static JSON (generated by scripts/process-sigesguarda.ts)
  try {
    const res = await fetch('/data/ocorrencias-por-bairro.json')
    if (res.ok) {
      const data: BairroCrimeData[] = await res.json()
      if (data.length > 0) {
        cacheSet(CACHE_KEY, data)
        return data
      }
    }
  } catch {
    // Static file not available
  }

  return []
}
